#!/usr/bin/env bash
# V1 Release Gate 1: Adversarial subagent E2E test
#
# Tests that pm-strategy produces a STRATEGY.md containing a non-trivial
# "## Challenged by adversarial review" section (>50 chars of content).
#
# This test requires Claude Code (`claude` CLI) to be available and authenticated.
# It creates a temp project directory with synthetic context and runs pm-strategy.
#
# Usage: bash test/adversarial.e2e.sh
# Exit 0 = pass, exit 1 = fail
set -euo pipefail

_REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
_TMPDIR=$(mktemp -d /tmp/nanopm-adversarial-XXXXXX)

cleanup() { rm -rf "$_TMPDIR"; }
trap cleanup EXIT

ok()   { printf '  \033[0;32m✓\033[0m %s\n' "$*"; }
fail() { printf '  \033[0;31m✗\033[0m %s\n' "$*"; exit 1; }

echo
echo "  nanopm E2E: adversarial subagent gate"
echo "  ======================================="
echo "  Temp dir: $_TMPDIR"
echo

# ── check claude CLI available ────────────────────────────────────────────────
if ! command -v claude >/dev/null 2>&1; then
  printf '  \033[0;33m⚠\033[0m claude CLI not found — skipping E2E test\n'
  echo "  (Install Claude Code to run this gate)"
  exit 0
fi
ok "claude CLI found"

# ── set up temp project ───────────────────────────────────────────────────────
cd "$_TMPDIR"
git init -q
mkdir -p .nanopm

# Synthetic audit with a clear strategic framing
cat > .nanopm/AUDIT.md <<'EOF'
# Product Audit
Generated by /pm-audit on 2026-01-01
Project: test-project

---

## 1. What You're Actually Building

A project management tool for solo founders who need to track their own work without
the overhead of Jira or Linear. The core behavior is a simple kanban board with AI
summaries of weekly progress.

---

## 2. Who You're Actually Building It For

Solo technical founders, ages 25-40, running pre-seed or bootstrapped products.
The stated target was "teams of 5-20" but every active user is a solo operator.

---

## 3. The Biggest Strategic Gap Right Now

The product is being positioned as a team tool (pricing, messaging) but 90% of
active users are solos. This positioning mismatch is causing confusion in onboarding
and churn after trial.

---

## 4. The Question You're Avoiding

Are solo founders actually willing to pay for productivity tooling, or do they
just use whatever is free and good enough?

---

## 5. Recommended Next Skill

**Run: /pm-objectives**
EOF

# Synthetic objectives
cat > .nanopm/OBJECTIVES.md <<'EOF'
# Product Objectives
Generated by /pm-objectives on 2026-01-01
Project: test-project
Period: Q1 2026

---

## Objective 1: Validate solo founder as paying segment

| Key Result | Target | Metric |
|-----------|--------|--------|
| KR1: Paying solo users | 50 | Monthly active paying accounts |
| KR2: Conversion rate | >10% | Trial to paid |
| KR3: Churn | <5% | Monthly churn of paying solos |
EOF

# Copy lib so nanopm_preamble is available
mkdir -p .claude/skills/nanopm/lib
cp "$_REPO_ROOT/lib/nanopm.sh" .claude/skills/nanopm/lib/nanopm.sh
cp -r "$_REPO_ROOT/pm-strategy" .claude/skills/nanopm/pm-strategy

echo
echo "  Synthetic project ready. Running pm-strategy via claude..."
echo "  (This will take 30-90 seconds)"
echo

# ── run pm-strategy non-interactively ────────────────────────────────────────
# We use claude --print with a prompt that simulates what the skill does,
# specifically Phase 4 (adversarial) + Phase 6 (write STRATEGY.md).
# We don't invoke the full interactive skill — we test the output contract.

_PROMPT='You are running the pm-strategy nanopm skill in non-interactive mode.

Context files are available at:
- .nanopm/AUDIT.md
- .nanopm/OBJECTIVES.md

Task:
1. Read the audit and objectives.
2. Draft a 3-sentence product strategy.
3. Dispatch an adversarial subagent (using the Agent tool) to challenge the strategy.
   The subagent must answer exactly three questions:
   1. ASSUMPTION: the single most important assumption the strategy makes
   2. FALSIFICATION: specific evidence that would prove it wrong
   3. CHEAPEST TEST: one action this week that would confirm or deny the assumption
4. Write .nanopm/STRATEGY.md containing:
   - ## The Bet (one sentence)
   - ## How We Win (2 bullets)
   - ## The Risk (one sentence)
   - ## Challenged by adversarial review with these sub-fields:
       **Core assumption:** ...
       **What would falsify it:** ...
       **Cheapest test:** ...
       **Response:** ...
5. When done, output exactly: STRATEGY_WRITTEN

Do not ask questions. Complete all steps autonomously.'

claude --print "$_PROMPT" > /tmp/nanopm-adversarial-output.txt 2>&1 || true

# ── verify output ─────────────────────────────────────────────────────────────
echo
echo "  Verifying STRATEGY.md..."

# Check file was created
if [ ! -f ".nanopm/STRATEGY.md" ]; then
  fail "STRATEGY.md not created"
fi
ok "STRATEGY.md exists"

# Check required top-level sections
_sections=("## The Bet" "## How We Win" "## The Risk" "## Challenged by adversarial review")
for section in "${_sections[@]}"; do
  if grep -q "$section" .nanopm/STRATEGY.md; then
    ok "Section present: $section"
  else
    fail "Section missing: $section"
  fi
done

# Check adversarial section has >50 chars of content (V1 gate)
_challenge_content=$(awk '/^## Challenged by adversarial review/{p=1;next} /^## /{p=0} p' .nanopm/STRATEGY.md | tr -d '[:space:]')
_challenge_len=${#_challenge_content}
if [ "$_challenge_len" -gt 50 ]; then
  ok "Adversarial section has content (${_challenge_len} chars — gate requires >50)"
else
  fail "Adversarial section too short (${_challenge_len} chars — gate requires >50). V1 release gate FAILED."
fi

# Check structured adversarial sub-fields are present
_structured_fields=("Core assumption:" "What would falsify it:" "Cheapest test:")
for field in "${_structured_fields[@]}"; do
  if grep -q "$field" .nanopm/STRATEGY.md; then
    ok "Structured field present: $field"
  else
    fail "Structured field missing: $field (adversarial output is not using new 3-field format)"
  fi
done

echo
echo "  ─────────────────────────────"
echo "  RESULT: PASSED — adversarial subagent gate OK"
exit 0
