import Foundation

enum Phase: String, CaseIterable, Identifiable, Sendable {
    case define = "Define"
    case discover = "Discover"
    case plan = "Plan"
    case ship = "Build"
    case daily = "Day to Day"
    // Catch-all for markdown under .nanopm/ that maps to no other phase
    // (e.g. a hand-written note, or a doc from a future layout). Ordered last
    // so it sits at the bottom of the sidebar. Has no skills/overview.
    case other = "Others"

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .define: return "book.closed"
        case .discover: return "magnifyingglass"
        case .plan: return "map"
        case .ship: return "hammer"
        case .daily: return "sun.max"
        case .other: return "tray.full"
        }
    }

    var order: Int { Phase.allCases.firstIndex(of: self) ?? 0 }
}

/// Helpers for PRD artifacts (the `prds/` subfolder of .nanopm/).
enum PRDFiles {
    static func isPRD(_ relativePath: String) -> Bool {
        relativePath.hasPrefix("prds/") && relativePath.hasSuffix(".md")
    }

    /// Parses the PRD/pitch header for a display title and status.
    static func summary(from content: String, fallbackName: String) -> (title: String, status: String?, date: String?) {
        var title = fallbackName
        var status: String?
        var date: String?
        for line in content.components(separatedBy: "\n").prefix(12) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if title == fallbackName,
               let range = trimmed.range(of: #"^#\s+(PRD|Pitch):\s+"#, options: .regularExpression) {
                title = String(trimmed[range.upperBound...]).trimmingCharacters(in: .whitespaces)
            } else if let r = trimmed.range(of: "Status:") {
                status = String(trimmed[r.upperBound...]).trimmingCharacters(in: .whitespaces)
            } else if let r = trimmed.range(of: "Generated by /pm-prd on ") {
                date = String(trimmed[r.upperBound...]).trimmingCharacters(in: .whitespaces)
            }
        }
        return (title, status, date)
    }
}

/// Helpers for reasoning sidecars (the `reasoning/` subfolder of .nanopm/).
/// Each Define skill writes a clean, share-ready doc plus
/// `reasoning/<same filename>` carrying the Evidenced/Assumed calls, sources,
/// and rationale. The path convention mirrors `nanopm_reasoning_path` in
/// lib/nanopm.sh — change one and you must change the other. Sidecars are
/// never listed in the sidebar; they surface as a "Reasoning" pane on their
/// clean doc's detail view.
enum ReasoningFiles {
    static func isReasoning(_ relativePath: String) -> Bool {
        relativePath.hasPrefix("reasoning/")
    }

    /// "VISION-MISSION.md" → "reasoning/VISION-MISSION.md"
    static func sidecarPath(for relativePath: String) -> String {
        "reasoning/" + (relativePath as NSString).lastPathComponent
    }
}

struct Project: Identifiable, Hashable, Sendable {
    let path: String

    var id: String { path }
    var name: String { (path as NSString).lastPathComponent }
    var nanopmPath: String { path + "/.nanopm" }
}

struct Artifact: Identifiable, Hashable, Sendable {
    /// Path relative to .nanopm/
    let relativePath: String
    let phase: Phase
    let modifiedAt: Date

    var id: String { relativePath }
    var fileName: String { (relativePath as NSString).lastPathComponent }
    var isMarkdown: Bool { relativePath.lowercased().hasSuffix(".md") }

    var displayName: String { prettyDocName(relativePath) }

    /// The consolidated briefs render as cards atop their phase overview, never as
    /// sidebar rows. vNext lives at wiki/overview/{company,current-work}.md (matched
    /// by full path — the filenames are too generic to match alone); the legacy flat
    /// CONTEXT-SUMMARY / PLAN-SUMMARY are matched case-insensitively by filename (a
    /// subagent may write any case, and on a case-sensitive filesystem an exact-string
    /// match would silently miss it — leaving the brief both in the sidebar AND absent
    /// from its card).
    var isPhaseBrief: Bool {
        let p = relativePath.lowercased()
        if p == "wiki/overview/company.md" || p == "wiki/overview/current-work.md" { return true }
        let f = fileName.lowercased()
        return f == "context-summary.md" || f == "plan-summary.md"
    }
}

/// "STRATEGY.md" → "Strategy", "prds/foo-bar.md" → "foo-bar"
func prettyDocName(_ relativePath: String) -> String {
    let file = (relativePath as NSString).lastPathComponent
    var base = (file as NSString).deletingPathExtension
    if base == base.uppercased() { base = base.capitalized }
    return base
}

/// `.nanopm/opportunities/` is the Discovery Opportunity DB (an LLM-wiki):
/// one `<slug>.md` per opportunity plus a ranked `INDEX.md`, an append-only
/// `LOG.md`, and an editable `SCHEMA.md`. These are grouped under one
/// expandable "Opportunities" entry in Discover (INDEX is the landing), not
/// listed as flat sidebar rows — mirroring how PRDs and Competitors collapse.
enum OpportunityFiles {
    static let dirPrefix = "opportunities/"

    static func isOpportunityFile(_ relativePath: String) -> Bool {
        relativePath.lowercased().hasPrefix(dirPrefix)
    }

    private static func basename(_ relativePath: String) -> String {
        (relativePath as NSString).lastPathComponent.lowercased()
    }

    /// The ranked home page; the "Opportunities" entry opens this.
    static func isIndex(_ relativePath: String) -> Bool {
        isOpportunityFile(relativePath) && basename(relativePath) == "index.md"
    }

    /// INDEX / LOG / SCHEMA are the DB's machinery, not individual opportunities.
    static func isReserved(_ relativePath: String) -> Bool {
        isOpportunityFile(relativePath)
            && ["index.md", "log.md", "schema.md"].contains(basename(relativePath))
    }
}

/// Fixed artifact → phase mapping. Files that match no rule are internal
/// state (configs, logs, snapshots) and are not surfaced in the viewer.
enum PhaseMapper {
    // "context" matches CONTEXT-SUMMARY.md (the consolidated brief) and the legacy
    // CONTEXT.md manual-ingestion fallback — both belong to Define.
    private static let defineNames = ["vision", "mission", "business", "org", "product", "personas", "context"]
    private static let discoverNames = ["feedback", "data", "discovery", "interview", "competitor"]
    // "plan" matches PLAN-SUMMARY.md (the consolidated current-work brief) — the
    // Plan-phase counterpart to CONTEXT-SUMMARY.md, rendered atop the Plan overview.
    private static let planNames = ["objectives", "strategy", "roadmap", "prd", "plan"]
    private static let shipNames = ["breakdown", "handoff", "retro", "tasks"]
    // "audit" is the legacy name for "challenges" (pre /pm-challenge-me rename).
    private static let dailyNames = ["challenge", "audit", "standup", "weekly", "update"]

    static func phase(for relativePath: String) -> Phase? {
        let lower = relativePath.lowercased()
        let file = (lower as NSString).lastPathComponent

        // vNext wiki layout (.nanopm/wiki/ + raw/). Overviews and entity pages are
        // canonical here and map to their phase; index/log/_review and the raw/
        // source layer are machinery (hidden); NANOPM-WIKI.md is the schema (hidden).
        // wiki/docs/ holds not-yet-canonical copies of the root skill docs — skills
        // still read/write the root files, so it stays hidden to avoid double-listing
        // until skills migrate to write there.
        if lower == "nanopm-wiki.md" { return nil }
        if lower.hasPrefix("raw/") { return nil }
        if lower.hasPrefix("wiki/") {
            if file == "index.md" || file == "log.md" { return nil }
            if lower.hasPrefix("wiki/_review/") || lower.hasPrefix("wiki/docs/") { return nil }
            if lower == "wiki/overview/company.md" { return .define }
            if lower == "wiki/overview/current-work.md" { return .plan }
            if lower.hasPrefix("wiki/entities/personas/")
                || lower.hasPrefix("wiki/entities/features/")
                || lower.hasPrefix("wiki/entities/people/") { return .define }
            if lower.hasPrefix("wiki/entities/competitors/")
                || lower.hasPrefix("wiki/entities/opportunities/") { return .discover }
            if lower.hasPrefix("wiki/entities/objectives/") { return .plan }
            return lower.hasSuffix(".md") ? .other : nil
        }

        if lower.hasPrefix("prds/") { return .ship }
        // intel/ belongs to the Competitors section, which reads its reports
        // and snapshots out of the artifact store. opportunities/ is the
        // Discovery Opportunity DB (INDEX.md / SCHEMA.md / <slug>.md) — matched
        // by folder, since those filenames don't match any discoverNames prefix.
        if lower.hasPrefix("interviews/") || lower.hasPrefix("competitors/") || lower.hasPrefix("intel/") || lower.hasPrefix("opportunities/") {
            return .discover
        }
        if lower.hasPrefix("breakdowns/") || lower.hasPrefix("handoffs/") { return .ship }
        // Breakdown task files are handoff outputs (they go to external trackers);
        // not surfaced in the browser. Explicit so a slug like "discovery-*" can't
        // fall through to a filename-prefix phase match below and land in Discover.
        if lower.hasPrefix("tasks/") { return nil }

        // reasoning/ sidecars mirror their clean doc's filename, so the
        // name-prefix matching below assigns them the same phase. They're
        // kept in the store (the detail view pairs them) but hidden from
        // the sidebar by ProjectView.
        if defineNames.contains(where: { file.hasPrefix($0) }) { return .define }
        if discoverNames.contains(where: { file.hasPrefix($0) }) { return .discover }
        if planNames.contains(where: { file.hasPrefix($0) }) { return .plan }
        if shipNames.contains(where: { file.hasPrefix($0) }) { return .ship }
        if dailyNames.contains(where: { file.hasPrefix($0) }) { return .daily }
        // Any remaining markdown is surfaced under "Others" rather than dropped
        // silently — so a hand-written note or a doc from a future layout stays
        // visible. Stray json/jsonl (e.g. competitors.json, decision.jsonl) keep
        // returning nil: they're data, not reading material. tasks/ already
        // returned nil above and stays hidden.
        if lower.hasSuffix(".md") { return .other }
        return nil
    }
}
