import Foundation

enum Phase: String, CaseIterable, Identifiable, Sendable {
    case define = "Define"
    case discover = "Discover"
    case plan = "Plan"
    case ship = "Build"
    case daily = "Day to Day"
    // Catch-all for markdown under .nanopm/ that maps to no other phase
    // (e.g. a hand-written note, or a doc from a future layout). Ordered last
    // so it sits at the bottom of the sidebar. Has no skills/overview.
    case other = "Others"

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .define: return "book.closed"
        case .discover: return "magnifyingglass"
        case .plan: return "map"
        case .ship: return "hammer"
        case .daily: return "sun.max"
        case .other: return "tray.full"
        }
    }

    var order: Int { Phase.allCases.firstIndex(of: self) ?? 0 }
}

/// Helpers for PRD artifacts. Under wiki-canonical writes PRDs live at
/// `wiki/docs/prds/`; the legacy `prds/` root path is kept for un-migrated projects.
enum PRDFiles {
    static func isPRD(_ relativePath: String) -> Bool {
        (relativePath.hasPrefix("wiki/docs/prds/") || relativePath.hasPrefix("prds/"))
            && relativePath.hasSuffix(".md")
    }

    /// Parses the PRD/pitch header for a display title and status.
    static func summary(from content: String, fallbackName: String) -> (title: String, status: String?, date: String?) {
        var title = fallbackName
        var status: String?
        var date: String?
        for line in content.components(separatedBy: "\n").prefix(12) {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            if title == fallbackName,
               let range = trimmed.range(of: #"^#\s+(PRD|Pitch):\s+"#, options: .regularExpression) {
                title = String(trimmed[range.upperBound...]).trimmingCharacters(in: .whitespaces)
            } else if let r = trimmed.range(of: "Status:") {
                status = String(trimmed[r.upperBound...]).trimmingCharacters(in: .whitespaces)
            } else if let r = trimmed.range(of: "Generated by /pm-prd on ") {
                date = String(trimmed[r.upperBound...]).trimmingCharacters(in: .whitespaces)
            }
        }
        return (title, status, date)
    }
}

/// Helpers for a doc's reasoning surface. Under **wiki-canonical writes** each doc
/// page carries its rationale inline in a `## Provenance & assumptions` section
/// (schema §4.3/§5) — there is no separate `reasoning/` file. The viewer surfaces
/// that section in a "Reasoning" window. The coupling that used to be
/// `nanopm_reasoning_path` ↔ a sidecar file is now this section ↔ the page (NANOPM-WIKI
/// §12). Legacy projects (pre-migration, or not-yet-routed skills like
/// competitors-intel) still have a `reasoning/<doc>.md` sidecar; `isReasoning` /
/// `sidecarPath` keep working for them as a fallback.
enum ReasoningFiles {
    /// The line-start heading that opens a page's inline provenance section.
    static let provenanceHeading = "## Provenance & assumptions"

    static func isReasoning(_ relativePath: String) -> Bool {
        relativePath.hasPrefix("reasoning/")
    }

    /// "VISION-MISSION.md" → "reasoning/VISION-MISSION.md" (legacy sidecar fallback).
    static func sidecarPath(for relativePath: String) -> String {
        "reasoning/" + (relativePath as NSString).lastPathComponent
    }

    /// A line IS the provenance heading. Trailing-only trim so this matches exactly
    /// the set `bin/nanopm-migrate-to-wiki`'s `has_provenance` (Python `rstrip()`)
    /// accepts — the heading at column 0. Keep the two in lockstep (NANOPM-WIKI §12).
    private static func isProvenanceHeading(_ line: String) -> Bool {
        String(line.reversed().drop { $0 == " " || $0 == "\t" }.reversed()) == provenanceHeading
    }

    /// True if a doc page carries an inline provenance section (heading matched at
    /// line start, so a mention in prose or a code fence can't false-positive).
    static func hasProvenance(_ content: String) -> Bool {
        content.components(separatedBy: "\n").contains(where: isProvenanceHeading)
    }

    /// Extract the provenance section — from its heading through the next top-level
    /// `## ` heading or end of file — or nil if the page has none. Lets the Reasoning
    /// window show just the rationale, not the whole clean doc.
    static func extractProvenance(_ content: String) -> String? {
        let lines = content.components(separatedBy: "\n")
        guard let start = lines.firstIndex(where: isProvenanceHeading) else { return nil }
        var end = lines.count
        var i = start + 1
        while i < lines.count {
            if lines[i].hasPrefix("## ") { end = i; break }
            i += 1
        }
        return lines[start..<end].joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }
}

struct Project: Identifiable, Hashable, Sendable {
    let path: String

    var id: String { path }
    var name: String { (path as NSString).lastPathComponent }
    var nanopmPath: String { path + "/.nanopm" }
}

struct Artifact: Identifiable, Hashable, Sendable {
    /// Path relative to .nanopm/
    let relativePath: String
    let phase: Phase
    let modifiedAt: Date

    var id: String { relativePath }
    var fileName: String { (relativePath as NSString).lastPathComponent }
    var isMarkdown: Bool { relativePath.lowercased().hasSuffix(".md") }

    var displayName: String { prettyDocName(relativePath) }

    /// The consolidated briefs render as cards atop their phase overview, never as
    /// sidebar rows. vNext lives at wiki/overview/{company,current-work}.md (matched
    /// by full path — the filenames are too generic to match alone); the legacy flat
    /// CONTEXT-SUMMARY / PLAN-SUMMARY are matched case-insensitively by filename (a
    /// subagent may write any case, and on a case-sensitive filesystem an exact-string
    /// match would silently miss it — leaving the brief both in the sidebar AND absent
    /// from its card).
    var isPhaseBrief: Bool {
        let p = relativePath.lowercased()
        if p == "wiki/overview/company.md" || p == "wiki/overview/current-work.md" { return true }
        let f = fileName.lowercased()
        return f == "context-summary.md" || f == "plan-summary.md"
    }
}

/// Strip a leading YAML frontmatter block (--- … ---) so a doc renders as prose,
/// not a "key: value …" metadata paragraph. The vNext wiki pages (overviews,
/// entities) carry frontmatter; this keeps the reading views clean. No-op when
/// there's no frontmatter or no closing fence.
func stripFrontmatter(_ raw: String) -> String {
    guard raw.hasPrefix("---") else { return raw }
    let lines = raw.components(separatedBy: "\n")
    var i = 1
    while i < lines.count {
        if lines[i].trimmingCharacters(in: .whitespaces) == "---" {
            return lines[(i + 1)...].joined(separator: "\n")
                .trimmingCharacters(in: .newlines)
        }
        i += 1
    }
    return raw
}

/// "STRATEGY.md" → "Strategy", "prds/foo-bar.md" → "foo-bar"
func prettyDocName(_ relativePath: String) -> String {
    let file = (relativePath as NSString).lastPathComponent
    var base = (file as NSString).deletingPathExtension
    if base == base.uppercased() { base = base.capitalized }
    return base
}

/// `.nanopm/opportunities/` is the Discovery Opportunity DB (an LLM-wiki):
/// one `<slug>.md` per opportunity plus a ranked `INDEX.md`, an append-only
/// `LOG.md`, and an editable `SCHEMA.md`. These are grouped under one
/// expandable "Opportunities" entry in Discover (INDEX is the landing), not
/// listed as flat sidebar rows — mirroring how PRDs and Competitors collapse.
enum OpportunityFiles {
    /// Canonical home under wiki-canonical writes (schema §2); the legacy root
    /// `opportunities/` path is kept for un-migrated projects.
    static let dirPrefix = "wiki/entities/opportunities/"
    static let legacyPrefix = "opportunities/"

    static func isOpportunityFile(_ relativePath: String) -> Bool {
        let l = relativePath.lowercased()
        return l.hasPrefix(dirPrefix) || l.hasPrefix(legacyPrefix)
    }

    private static func basename(_ relativePath: String) -> String {
        (relativePath as NSString).lastPathComponent.lowercased()
    }

    /// The ranked home page; the "Opportunities" entry opens this.
    static func isIndex(_ relativePath: String) -> Bool {
        isOpportunityFile(relativePath) && basename(relativePath) == "index.md"
    }

    /// INDEX / LOG / SCHEMA are the DB's machinery, not individual opportunities.
    static func isReserved(_ relativePath: String) -> Bool {
        isOpportunityFile(relativePath)
            && ["index.md", "log.md", "schema.md"].contains(basename(relativePath))
    }
}

/// `.nanopm/wiki/entities/solutions/` is the Solutions store (the OST node that
/// bridges an opportunity to a compared set of candidate solutions — written by
/// `/pm-solutions`): one `<slug>.md` per solution plus a generated `INDEX.md`,
/// an append-only `LOG.md`, and an editable `SCHEMA.md`. Like Opportunities,
/// these are grouped under one expandable "Solutions" entry (INDEX is the
/// landing), not listed as flat sidebar rows. Mirrors `OpportunityFiles`.
enum SolutionFiles {
    /// Canonical home (PRD §Scope/§Requirements); the legacy root `solutions/`
    /// path is kept for symmetry with the other entity types.
    static let dirPrefix = "wiki/entities/solutions/"
    static let legacyPrefix = "solutions/"

    static func isSolutionFile(_ relativePath: String) -> Bool {
        let l = relativePath.lowercased()
        return l.hasPrefix(dirPrefix) || l.hasPrefix(legacyPrefix)
    }

    private static func basename(_ relativePath: String) -> String {
        (relativePath as NSString).lastPathComponent.lowercased()
    }

    /// The home page; the "Solutions" entry opens this.
    static func isIndex(_ relativePath: String) -> Bool {
        isSolutionFile(relativePath) && basename(relativePath) == "index.md"
    }

    /// INDEX / LOG / SCHEMA are the store's machinery, not individual solutions.
    static func isReserved(_ relativePath: String) -> Bool {
        isSolutionFile(relativePath)
            && ["index.md", "log.md", "schema.md"].contains(basename(relativePath))
    }
}

/// Fixed artifact → phase mapping. Files that match no rule are internal
/// state (configs, logs, snapshots) and are not surfaced in the viewer.
enum PhaseMapper {
    // "context" matches CONTEXT-SUMMARY.md (the consolidated brief) and the legacy
    // CONTEXT.md manual-ingestion fallback — both belong to Define.
    private static let defineNames = ["vision", "mission", "business", "org", "product", "personas", "context"]
    private static let discoverNames = ["feedback", "data", "discovery", "interview", "competitor"]
    // "plan" matches PLAN-SUMMARY.md (the consolidated current-work brief) — the
    // Plan-phase counterpart to CONTEXT-SUMMARY.md, rendered atop the Plan overview.
    private static let planNames = ["objectives", "strategy", "roadmap", "prd", "plan"]
    private static let shipNames = ["breakdown", "handoff", "retro", "tasks"]
    // "audit" is the legacy name for "challenges" (pre /pm-challenge-me rename).
    private static let dailyNames = ["challenge", "audit", "standup", "weekly", "update"]

    static func phase(for relativePath: String) -> Phase? {
        let lower = relativePath.lowercased()
        let file = (lower as NSString).lastPathComponent

        // vNext wiki layout (.nanopm/wiki/ + raw/) — now canonical (wiki-canonical
        // writes). Overviews + entity pages map to their phase; index/log and the
        // raw/ source layer are machinery (hidden); NANOPM-WIKI.md is the schema
        // (hidden). wiki/docs/ holds the migrated skill docs: prds/ -> Ship, the rest
        // fall through to the same filename matching the root docs used.
        if lower == "nanopm-wiki.md" { return nil }
        // raw/ is the immutable source layer — hidden from the browser — EXCEPT the
        // competitor intel (snapshots + dated INTEL reports), which the Competitors
        // section reads from the store and groups on its own page.
        if lower.hasPrefix("raw/competitors/") { return .discover }
        if lower.hasPrefix("raw/") { return nil }
        if lower.hasPrefix("wiki/") {
            if file == "index.md" || file == "log.md" { return nil }
            if lower == "wiki/overview/company.md" { return .define }
            if lower == "wiki/overview/current-work.md" { return .plan }
            if lower.hasPrefix("wiki/entities/personas/")
                || lower.hasPrefix("wiki/entities/features/")
                || lower.hasPrefix("wiki/entities/people/") { return .define }
            if lower.hasPrefix("wiki/entities/competitors/")
                || lower.hasPrefix("wiki/entities/opportunities/")
                // Solutions are the OST node bridging an opportunity to a compared
                // set of candidates; grouped beside Opportunities under Discover.
                || lower.hasPrefix("wiki/entities/solutions/") { return .discover }
            if lower.hasPrefix("wiki/entities/objectives/") { return .plan }
            if lower.hasPrefix("wiki/docs/prds/") { return .ship }
            // handoffs/ are the human-readable handoff (the shareable ticket list) —
            // surfaced under Ship, as the root handoffs/ was.
            if lower.hasPrefix("wiki/docs/handoffs/") { return .ship }
            // tasks/ are pm-breakdown outputs bound for external trackers — relocated
            // into the wiki for storage but kept hidden from the browser (as before).
            if lower.hasPrefix("wiki/docs/tasks/") { return nil }
            // Dated series folders (weekly updates, standups): one page per period,
            // grouped under a "Weekly Updates" / "Standups" entry in Day to Day. Routed
            // by folder prefix — the filenames are bare dates, so the name match below
            // would otherwise miss them.
            if lower.hasPrefix("wiki/docs/weekly-updates/")
                || lower.hasPrefix("wiki/docs/standups/") { return .daily }
            // wiki/docs/<skill>.md: a migrated doc — fall through to the filename
            // matching below (vision/strategy/feedback/... -> phase). Any other wiki
            // markdown lands in "Other".
            if !lower.hasPrefix("wiki/docs/") {
                return lower.hasSuffix(".md") ? .other : nil
            }
            // fall through for wiki/docs/ files
        }

        if lower.hasPrefix("prds/") { return .ship }
        // intel/ belongs to the Competitors section, which reads its reports
        // and snapshots out of the artifact store. opportunities/ is the
        // Discovery Opportunity DB (INDEX.md / SCHEMA.md / <slug>.md) — matched
        // by folder, since those filenames don't match any discoverNames prefix.
        if lower.hasPrefix("interviews/") || lower.hasPrefix("competitors/") || lower.hasPrefix("intel/") || lower.hasPrefix("opportunities/") {
            return .discover
        }
        if lower.hasPrefix("breakdowns/") || lower.hasPrefix("handoffs/") { return .ship }
        // Breakdown task files are handoff outputs (they go to external trackers);
        // not surfaced in the browser. Explicit so a slug like "discovery-*" can't
        // fall through to a filename-prefix phase match below and land in Discover.
        if lower.hasPrefix("tasks/") { return nil }

        // reasoning/ sidecars mirror their clean doc's filename, so the
        // name-prefix matching below assigns them the same phase. They're
        // kept in the store (the detail view pairs them) but hidden from
        // the sidebar by ProjectView.
        if defineNames.contains(where: { file.hasPrefix($0) }) { return .define }
        if discoverNames.contains(where: { file.hasPrefix($0) }) { return .discover }
        if planNames.contains(where: { file.hasPrefix($0) }) { return .plan }
        if shipNames.contains(where: { file.hasPrefix($0) }) { return .ship }
        if dailyNames.contains(where: { file.hasPrefix($0) }) { return .daily }
        // Any remaining markdown is surfaced under "Others" rather than dropped
        // silently — so a hand-written note or a doc from a future layout stays
        // visible. Stray json/jsonl (e.g. competitors.json, decision.jsonl) keep
        // returning nil: they're data, not reading material. tasks/ already
        // returned nil above and stays hidden.
        if lower.hasSuffix(".md") { return .other }
        return nil
    }
}
