import SwiftUI
import MarkdownUI

/// Recap page for a phase: every runnable skill, its status
/// (generated / running / waiting / missing), and a Run action. Shared by
/// Discover, Planning, and Build.
struct PhaseOverviewView: View {
    let phase: Phase
    @ObservedObject var store: ArtifactStore
    @EnvironmentObject private var runManager: RunManager
    /// Open a route — an artifact id, a folder page, or a run session.
    let onOpen: (String) -> Void
    let onAnswer: (String) -> Void

    @State private var claudeAvailable: Bool?
    /// Rendered content of the consolidated context brief, shown atop Define.
    @State private var briefContent: String?

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 18) {
                VStack(alignment: .leading, spacing: 6) {
                    Text(phase.rawValue)
                        .font(.npDisplay(30))
                        .foregroundStyle(Color.npInk)
                    Text(SkillCatalog.subtitle(for: phase))
                        .font(.callout)
                        .foregroundStyle(.secondary)
                }

                if phase == .define {
                    contextBriefCard
                }

                if claudeAvailable == false {
                    Label("The `claude` CLI was not found in your shell PATH — run actions are disabled.",
                          systemImage: "exclamationmark.triangle")
                        .font(.callout)
                        .foregroundStyle(Color.npAmber)
                        .padding(10)
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .background(Color.npAmber.opacity(0.10), in: RoundedRectangle(cornerRadius: 8))
                }

                ForEach(SkillCatalog.docs(for: phase)) { doc in
                    row(doc)
                }

                Text("Runs execute the skill through the `claude` CLI in the project folder — keep the app open while a run is in flight. You can keep browsing; you'll be notified when the model needs your input and when the document is ready.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            .padding(28)
            .frame(maxWidth: 860, alignment: .leading)
            .frame(maxWidth: .infinity)
        }
        .background(Color.npPaper)
        .task { await checkClaude() }
    }

    /// Consolidated PM context brief, regenerated by a subagent after each Define
    /// skill and reloaded into every skill's preamble. Rendered inline at the top
    /// of the Define phase so it's the first thing seen on click.
    @ViewBuilder
    private var contextBriefCard: some View {
        let brief = store.artifacts.first { $0.relativePath == "CONTEXT-SUMMARY.md" }

        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 10) {
                Image(systemName: "doc.richtext")
                    .font(.title3)
                    .foregroundStyle(Color.npCoral)
                    .frame(width: 34, height: 34)
                    .background(Color.npCoral.opacity(0.16), in: RoundedRectangle(cornerRadius: 8))
                VStack(alignment: .leading, spacing: 2) {
                    Text("Context Brief").font(.headline)
                    if let brief {
                        Text("The context every skill reloads · updated \(brief.modifiedAt.formatted(.relative(presentation: .named)))")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    } else {
                        Text("The consolidated company & product context every skill reloads.")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                            .fixedSize(horizontal: false, vertical: true)
                    }
                }
                Spacer(minLength: 12)
            }

            if brief != nil {
                Divider().overlay(Color.npCoral.opacity(0.20))
                if let briefContent {
                    Markdown(briefContent)
                        .markdownTheme(.nanopm)
                        .textSelection(.enabled)
                } else {
                    SparkleView(size: 16)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 24)
                }
            } else {
                Text("Generated automatically after your first Define skill runs.")
                    .font(.callout)
                    .foregroundStyle(.tertiary)
            }
        }
        .padding(16)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(Color.npCoral.opacity(0.06), in: RoundedRectangle(cornerRadius: 12))
        .overlay(RoundedRectangle(cornerRadius: 12).strokeBorder(Color.npCoral.opacity(brief != nil ? 0.30 : 0.15)))
        .task(id: "\(brief?.id ?? "none")#\(store.generation)") { await loadBrief() }
    }

    private func loadBrief() async {
        guard let brief = store.artifacts.first(where: { $0.relativePath == "CONTEXT-SUMMARY.md" }) else {
            briefContent = nil
            return
        }
        briefContent = (try? await store.content(of: brief)).map(Self.stripBriefHeader)
    }

    /// Drop the document's own H1 title and the "Generated … · Sources …" metadata
    /// line: the card header already carries the title and the update time, so the
    /// rendered body starts straight at the first section.
    private static func stripBriefHeader(_ raw: String) -> String {
        var lines = raw.components(separatedBy: "\n")
        func dropLeadingBlanks() {
            while let first = lines.first,
                  first.trimmingCharacters(in: .whitespaces).isEmpty {
                lines.removeFirst()
            }
        }
        dropLeadingBlanks()
        if let first = lines.first, first.hasPrefix("# ") { lines.removeFirst() }
        dropLeadingBlanks()
        if let first = lines.first, first.hasPrefix("Generated") { lines.removeFirst() }
        dropLeadingBlanks()
        return lines.joined(separator: "\n")
    }

    @ViewBuilder
    private func row(_ doc: SkillDoc) -> some View {
        let run = runManager.latestRun(for: doc.trackingPath, in: store.project.path)
        let isRunning = run?.status == .running
        let isWaiting = run?.pendingQuestions.isEmpty == false

        HStack(alignment: .top, spacing: 14) {
            Image(systemName: doc.icon)
                .font(.title3)
                .foregroundStyle(Color.npCoral)
                .frame(width: 34, height: 34)
                .background(Color.npCoral.opacity(0.10), in: RoundedRectangle(cornerRadius: 8))

            VStack(alignment: .leading, spacing: 4) {
                Text(doc.title).font(.headline)
                Text(doc.blurb)
                    .font(.callout)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)

                statusLine(doc, run: run, isRunning: isRunning, isWaiting: isWaiting)
            }

            Spacer(minLength: 12)

            if doc.skillCommand != nil {
                SkillRunButton(doc: doc, store: store,
                               claudeAvailable: claudeAvailable, onAnswer: onAnswer)
            }
        }
        .padding(14)
        .background(Color.npSurface.opacity(0.55), in: RoundedRectangle(cornerRadius: 10))
        .overlay(RoundedRectangle(cornerRadius: 10).strokeBorder(Color.npBorder))
    }

    @ViewBuilder
    private func statusLine(_ doc: SkillDoc, run: RunManager.SkillRun?,
                            isRunning: Bool, isWaiting: Bool) -> some View {
        if isRunning, let run {
            ThinkingIndicator(startedAt: run.startedAt, compact: true)
        } else if isWaiting {
            Button {
                onAnswer(doc.trackingPath)
            } label: {
                Label("Needs your input — answer to continue", systemImage: "questionmark.bubble.fill")
            }
            .buttonStyle(.link)
            .font(.caption)
            .tint(Color.npAmber)
        } else {
            outputStatus(doc)
            if case .failed(let message)? = run?.status {
                Label(String(message.prefix(120)), systemImage: "exclamationmark.triangle")
                    .font(.caption)
                    .foregroundStyle(Color.npRust)
            }
        }
    }

    /// Status driven by what the skill produces.
    @ViewBuilder
    private func outputStatus(_ doc: SkillDoc) -> some View {
        switch doc.output {
        case .file(let path):
            if let artifact = store.artifacts.first(where: { $0.relativePath == path }) {
                openLink(artifact.fileName, route: artifact.id,
                         subtitle: "updated \(artifact.modifiedAt.formatted(.relative(presentation: .named)))")
            } else {
                notYet
            }
        case .folder(let prefix, let opens):
            let count = store.artifacts.filter { $0.relativePath.hasPrefix(prefix) }.count
            if count > 0 {
                openLink(count == 1 ? "1 document" : "\(count) documents", route: opens, subtitle: nil)
            } else {
                notYet
            }
        case .handoff(let note):
            Text(note)
                .font(.caption)
                .foregroundStyle(.tertiary)
        }
    }

    private func openLink(_ label: String, route: String, subtitle: String?) -> some View {
        HStack(spacing: 6) {
            Button { onOpen(route) } label: {
                Label(label, systemImage: "arrow.up.right.square")
            }
            .buttonStyle(.link)
            if let subtitle {
                Text("· \(subtitle)")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    private var notYet: some View {
        Text("Not generated yet")
            .font(.caption)
            .foregroundStyle(.tertiary)
    }

    private func checkClaude() async {
        claudeAvailable = await ShellRunner.claudeAvailable()
    }
}
